data:
  seed: 42
  input_file: data/medium-export-e6bf40a8b01915d7380f6f547e0dd25ddd791328d4d9fa3a77513e82e662373c/posts/2001-2025
    Net_generation_United_States_all_sectors_monthly.csv
  freq: MS
  n_splits: 5
model:
  alpha: 0.6
  horizon: 12
  season: 12
output:
  figures_dir: images
  figure_format: png
  figure_dpi: 100
  font_family: serif
  figsize:
  - 9
  - 4
